/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Font;
import practicaanalisis.Metodos2;

/**
 *
 * @author carlosruiz
 */
public class DetalleSplines extends javax.swing.JFrame {
    public static String res, tabIni, tabFin, ecua, titIni, titFin;
    public static boolean esLineal;

    /**
     * Creates new form DetalleSplines
     */
    public DetalleSplines(String resultado, String tablaIni, String tablaFin, String ecuaciones, String titulosIni, String titulosFin, boolean isLineal) {
        res = resultado;
        tabIni = tablaIni;       
        tabFin = tablaFin;
        ecua = ecuaciones;
        titIni = titulosIni;
        titFin = titulosFin;
        esLineal = isLineal;
        initComponents();
        jTextArea1.setText(ecua);
        String[] titulos1 = titulosIni.split(";");
        String[] titulos2 = titulosFin.split(";");
        Double[][] tablaInicial = new Double[titulos1.length][titulos1.length+1];
        Double[][] tablaFinal = new Double[titulos2.length][titulos2.length+1];
        System.out.println("TAMAÑO TITULOS");
        System.out.println(titulos1.length);
        System.out.println(titulos2.length);
        String[] arr1 = tabIni.split(":");
        String[] arr2 = tabFin.split(":");
        for (int i = 0; i < arr1.length; i++){
            System.out.println("TAMAÑO ARR");
            System.out.println(arr1.length);
            System.out.println(arr2.length);
            String[] fila1 = arr1[i].split(";");
            String[] fila2 = arr2[i].split(";");
            for(int j = 0; j < fila1.length; j++){
                System.out.println("TAMAÑO FILA");
                System.out.println(fila1.length);
                System.out.println(fila2.length);
                tablaInicial[i][j] = Double.parseDouble(fila1[j]);
                tablaFinal[i][j] = Double.parseDouble(fila2[j]);
            }
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                tablaInicial,
                titulos1
            ));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                tablaFinal,
                titulos2
            ));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar);
        botonRegresar.setBounds(210, 20, 80, 80);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 120, 890, 140);

        jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        jTable1.getTableHeader().setFont(new Font("Lucida Grande", Font.ITALIC, 24));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 340, 890, 140);

        jTable2.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        jTable2.getTableHeader().setFont(new Font("Lucida Grande", Font.ITALIC, 24));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setRowHeight(30);
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(60, 560, 890, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DetalleSplines.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        ResultadoSplines resultadoSplines = new ResultadoSplines(res, tabIni, tabFin, ecua, titIni, titFin, esLineal);
        resultadoSplines.setVisible(true);
        resultadoSplines.setSize(1024,768);
        resultadoSplines.setResizable(false);
        resultadoSplines.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
