/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author carlosruiz
 */
public class EtapasMetodosDirectos extends javax.swing.JFrame {

    public static String resultado;
    public static String matrizFinal;
    public static String matrizFinalL;
    public static String matrizFinalU;
    public static String etapas;
    public static int from;
    
    /**
     * Creates new form EtapasMetodosDirectos
     * @param res
     * @param matriz
     * @param eta
     */
    public EtapasMetodosDirectos(String res, String matriz, String eta) {
        initComponents();
        from = 0;
        resultado = res;
        matrizFinal = matriz;
        etapas = eta;
        jTextArea1.setText(etapas);
    }

    public EtapasMetodosDirectos(String res, String matrizL, String matrizU, String eta) {
        initComponents();
        from = 1;
        resultado = res;
        matrizFinalL = matrizL;
        matrizFinalU = matrizU;
        etapas = eta;
        jTextArea1.setText(etapas);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarEtapas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        regresarEtapas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        regresarEtapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarEtapasActionPerformed(evt);
            }
        });
        getContentPane().add(regresarEtapas);
        regresarEtapas.setBounds(70, 30, 80, 80);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 950, 600);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EtapasMatriz.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarEtapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarEtapasActionPerformed
        // TODO add your handling code here:
        if(from == 0){
            ResultadosMetodosDirectos resultadosMetodosDirectos = new ResultadosMetodosDirectos(resultado, matrizFinal, etapas);
            resultadosMetodosDirectos.setVisible(true);
            resultadosMetodosDirectos.setSize(1024,768);
            resultadosMetodosDirectos.setResizable(false);
            resultadosMetodosDirectos.setLocationRelativeTo(null);
            dispose();
        }else{
            ResultadosFactorizacionLU resultadosLU = new ResultadosFactorizacionLU(resultado, matrizFinalL,matrizFinalU, etapas);
            resultadosLU.setVisible(true);
            resultadosLU.setSize(1024,768);
            resultadosLU.setResizable(false);
            resultadosLU.setLocationRelativeTo(null);
            dispose();
        }
        
    }//GEN-LAST:event_regresarEtapasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton regresarEtapas;
    // End of variables declaration//GEN-END:variables
}
