/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Daniel Rendon M
 */
public class Funciones extends javax.swing.JFrame {

    /**
     * Creates new form Funciones
     */
    public Funciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fx = new javax.swing.JTextField();
        botonGuardarFunciones = new javax.swing.JButton();
        botonRegresarFunciones = new javax.swing.JButton();
        gx = new javax.swing.JTextField();
        fPrimaX = new javax.swing.JTextField();
        fDoblePrimaX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        fx.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(fx);
        fx.setBounds(230, 290, 660, 50);

        botonGuardarFunciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GuardarBoton.png"))); // NOI18N
        getContentPane().add(botonGuardarFunciones);
        botonGuardarFunciones.setBounds(340, 640, 380, 100);

        botonRegresarFunciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresarFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarFuncionesActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarFunciones);
        botonRegresarFunciones.setBounds(50, 100, 80, 80);

        gx.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        gx.setSize(new java.awt.Dimension(660, 50));
        getContentPane().add(gx);
        gx.setBounds(230, 360, 660, 50);

        fPrimaX.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        fPrimaX.setSize(new java.awt.Dimension(660, 50));
        getContentPane().add(fPrimaX);
        fPrimaX.setBounds(230, 430, 660, 50);

        fDoblePrimaX.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        fDoblePrimaX.setSize(new java.awt.Dimension(660, 50));
        getContentPane().add(fDoblePrimaX);
        fDoblePrimaX.setBounds(230, 510, 660, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Funciones.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarFuncionesActionPerformed
        // TODO add your handling code here:
        Ecuaciones1Var ec = new Ecuaciones1Var();
        ec.setVisible(true);
        ec.setSize(1024,768);
        ec.setResizable(false);
        ec.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarFuncionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarFunciones;
    private javax.swing.JButton botonRegresarFunciones;
    private javax.swing.JTextField fDoblePrimaX;
    private javax.swing.JTextField fPrimaX;
    private javax.swing.JTextField fx;
    private javax.swing.JTextField gx;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
