/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;
import practicaanalisis.Metodos2;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import practicaanalisis.Funcion;
import practicaanalisis.Metodos;
import practicaanalisis.Metodos2;

/**
 *
 * @author carlosruiz
 */
public class GaussSeidel extends javax.swing.JFrame {
    private static java.text.DecimalFormat sf = new java.text.DecimalFormat("0.#E0"); 

    /**
     * Creates new form GaussSeidel
     */
    public GaussSeidel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        ayudaGaussSeidel = new javax.swing.JButton();
        ayudaLambda = new javax.swing.JButton();
        toleranciaGaussSeidel = new javax.swing.JTextField();
        lambdaGaussSeidel = new javax.swing.JTextField();
        normaInfinito = new javax.swing.JRadioButton();
        normaEuclidiana = new javax.swing.JRadioButton();
        botonCalcular = new javax.swing.JButton();
        iteracionesGaussSeidel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(174, 0, 5));
        jLabel2.setText("λ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 340, 30, 60);

        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar);
        botonRegresar.setBounds(60, 70, 80, 80);

        ayudaGaussSeidel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Ayuda.png"))); // NOI18N
        ayudaGaussSeidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaGaussSeidelActionPerformed(evt);
            }
        });
        getContentPane().add(ayudaGaussSeidel);
        ayudaGaussSeidel.setBounds(880, 50, 110, 110);

        ayudaLambda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonAyudaPequeno.png"))); // NOI18N
        ayudaLambda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaLambdaActionPerformed(evt);
            }
        });
        getContentPane().add(ayudaLambda);
        ayudaLambda.setBounds(210, 345, 50, 50);

        toleranciaGaussSeidel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        toleranciaGaussSeidel.setSize(new java.awt.Dimension(510, 40));
        getContentPane().add(toleranciaGaussSeidel);
        toleranciaGaussSeidel.setBounds(360, 290, 510, 40);

        lambdaGaussSeidel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(lambdaGaussSeidel);
        lambdaGaussSeidel.setBounds(270, 355, 600, 40);

        buttonGroup1.add(normaInfinito);
        getContentPane().add(normaInfinito);
        normaInfinito.setBounds(405, 415, 30, 23);

        buttonGroup1.add(normaEuclidiana);
        getContentPane().add(normaEuclidiana);
        normaEuclidiana.setBounds(865, 415, 30, 23);

        botonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalcularBoton.png"))); // NOI18N
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botonCalcular);
        botonCalcular.setBounds(540, 520, 370, 100);

        iteracionesGaussSeidel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        iteracionesGaussSeidel.setSize(new java.awt.Dimension(510, 40));
        getContentPane().add(iteracionesGaussSeidel);
        iteracionesGaussSeidel.setBounds(360, 210, 510, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gauss Seidel.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ayudaLambdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaLambdaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, null, "AYUDA - λ", HEIGHT, new javax.swing.ImageIcon(getClass().getResource("/imagenes/AyudaLambda.png")));
    }//GEN-LAST:event_ayudaLambdaActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        // TODO add your handling code here:
        double tol = 0;
        int iter = 0;
        double lambda = 0;
        boolean camposCorrectos = true;
        
        
        try{            
            tol = Double.parseDouble(toleranciaGaussSeidel.getText());
            iter = Integer.parseInt(iteracionesGaussSeidel.getText());
            lambda = Double.parseDouble(lambdaGaussSeidel.getText());
        }catch(Exception e){
            camposCorrectos = false;
        }
        
        if(iter <= 0 && tol <= 0 && (lambda < 0 || lambda > 2)){
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese información correcta a los campos, como un número mayor que cero para iteraciones, número mayor de cero para la tolerancia y un número para Lambda del rango (0,2)");
            camposCorrectos = false;
        }else if(iter <= 0){    
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un número mayor que cero para iteraciones");
            camposCorrectos = false;
        } else if(tol <= 0){
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un número mayor de cero para la tolerancia");
            camposCorrectos = false;
        } else if(lambda < 0 || lambda > 2){
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un número para Lambda del rango (0,2)");
            camposCorrectos = false;    
        } else{
            camposCorrectos = true;
        }
        
        normaInfinito.setActionCommand("0");
        normaEuclidiana.setActionCommand("1");
        int err = 0;
        try{
            err = Integer.parseInt(buttonGroup1.getSelection().getActionCommand());
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccionar el tipo de norma para trabajar");
            camposCorrectos = false;
        }
        
        if (camposCorrectos){
            if(Metodos2.tam != 0){
                Metodos2.gaussSeidelRelajado(Metodos2.a, Metodos2.b, Metodos2.tam, tol, iter, lambda, Metodos2.x, err);
                try {
                    String s = null;
                    
                    boolean error=false;
                    while ((s = Metodos2.stdError.readLine()) != null) {
                        JOptionPane.showMessageDialog(this,s,"Error",JOptionPane.ERROR_MESSAGE);
                        error=true;
                    } 
                    if(!error){
                        String output = "";
                        while ((s = Metodos2.stdOutput.readLine()) != null) {
                            System.out.println(s);
                            output = output + (s + "\n");
                        }
                        //INTERPRETAR S
                        String[] arrOutput = output.split("!");
                        
                        System.out.println(Arrays.toString(arrOutput));
                        String resultadoX = arrOutput[arrOutput.length-1];
                        System.out.println("TAMAÑOO");
                        System.out.println(arrOutput.length-1);
                        System.out.println(Metodos2.tam+2);
                        Object [][] tabla = new Object[arrOutput.length-1][Metodos2.tam+2];
                        for (int i = 0; i < arrOutput.length-1; i++) {
                            String temp = arrOutput[i];
                            System.out.println(temp);
                            temp = temp.replaceAll("\n", " ");
                            System.out.println(temp);
                            temp = temp.replace("[", "");
                            System.out.println(temp);
                            temp = temp.replace("]", "");
                            System.out.println(temp);
                            temp = temp.replace(",", "");
                            System.out.println(temp);
                            temp = temp.replaceAll("\\s+"," ");
                            System.out.println(temp);
                            
                            temp = temp.replace(" ", "!");
                            if(temp.charAt(0) == '!'){
                                temp = temp.substring(1,temp.length());
                            }
                            if(temp.charAt(temp.length()-1) == '!'){
                                temp = temp.substring(0,temp.length()-1);
                            }
                            //temp = temp.substring(1,temp.length()-1);
                            System.out.println(temp);
                            String[] arrTemp = temp.split("!");
                            
                            System.out.println(Arrays.toString(arrTemp));
                            
                            for (int j = 0; j < arrTemp.length; j++) {
                                if(j == 0){
                                    tabla[i][j] = arrTemp[j];
                                }else if(j == arrTemp.length-1){
                                    tabla[i][j] = sf.format(Double.parseDouble(arrTemp[j]));
                                }else{
                                    tabla[i][j] = Double.parseDouble(arrTemp[j]);
                                }
                            }
                            
                            
                            
                            
                            //String[] sFila = arrOutput[i].split("\n");
                            //Double[] fila = new Double[Metodos2.tam+2];
                            
                            //System.out.println(Arrays.toString(sFila));
                            
                        }
                        ResultadoGaussSeidel rgs = new ResultadoGaussSeidel(iter, tol, err, lambda, tabla, resultadoX);
                        rgs.setVisible(true);
                        rgs.setSize(1024,768);
                        rgs.setResizable(false);
                        rgs.setLocationRelativeTo(null);
                        dispose();
                    
                    }
                }catch (IOException ex) {
                    Logger.getLogger(Jacobi.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else{
            JOptionPane.showMessageDialog(rootPane, "Por favor asigne valores a su matriz");
            }
        }   
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void ayudaGaussSeidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaGaussSeidelActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, null, "AYUDA - Gauss Seidel", HEIGHT, new javax.swing.ImageIcon(getClass().getResource("/imagenes/AyudaGaussSeidel.png")));
    }//GEN-LAST:event_ayudaGaussSeidelActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        MetodosIterativos metodosIterativos = new MetodosIterativos();
        metodosIterativos.setVisible(true);
        metodosIterativos.setSize(1024,768);
        metodosIterativos.setResizable(false);
        metodosIterativos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GaussSeidel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ayudaGaussSeidel;
    private javax.swing.JButton ayudaLambda;
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField iteracionesGaussSeidel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField lambdaGaussSeidel;
    private javax.swing.JRadioButton normaEuclidiana;
    private javax.swing.JRadioButton normaInfinito;
    private javax.swing.JTextField toleranciaGaussSeidel;
    // End of variables declaration//GEN-END:variables
}
