/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author carlosruiz
 */
public class Jacobi extends javax.swing.JFrame {

    /**
     * Creates new form Jacobi
     */
    public Jacobi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        iteracionesJacobi = new javax.swing.JTextField();
        toleranciaJacobi = new javax.swing.JTextField();
        regresarJacobi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        normaInfinito = new javax.swing.JRadioButton();
        normaEuclidiana = new javax.swing.JRadioButton();
        botonCalcular = new javax.swing.JButton();
        ayudaLamba = new javax.swing.JButton();
        ayudaJacobi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        iteracionesJacobi.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(iteracionesJacobi);
        iteracionesJacobi.setBounds(360, 210, 510, 40);

        toleranciaJacobi.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(toleranciaJacobi);
        toleranciaJacobi.setBounds(360, 290, 510, 40);

        regresarJacobi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        regresarJacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarJacobiActionPerformed(evt);
            }
        });
        getContentPane().add(regresarJacobi);
        regresarJacobi.setBounds(140, 70, 80, 80);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(174, 10, 5));
        jLabel2.setText("λ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 350, 40, 40);

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(280, 355, 590, 40);

        buttonGroup1.add(normaInfinito);
        getContentPane().add(normaInfinito);
        normaInfinito.setBounds(405, 415, 30, 23);

        buttonGroup1.add(normaEuclidiana);
        getContentPane().add(normaEuclidiana);
        normaEuclidiana.setBounds(865, 415, 30, 23);

        botonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalcularBoton.png"))); // NOI18N
        getContentPane().add(botonCalcular);
        botonCalcular.setBounds(540, 520, 370, 100);

        ayudaLamba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonAyudaPequeno.png"))); // NOI18N
        getContentPane().add(ayudaLamba);
        ayudaLamba.setBounds(205, 345, 50, 50);

        ayudaJacobi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Ayuda.png"))); // NOI18N
        ayudaJacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaJacobiActionPerformed(evt);
            }
        });
        getContentPane().add(ayudaJacobi);
        ayudaJacobi.setBounds(730, 50, 110, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Jacobi.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ayudaJacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaJacobiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaJacobiActionPerformed

    private void regresarJacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarJacobiActionPerformed
        // TODO add your handling code here:
        MetodosIterativos metodosIterativos = new MetodosIterativos();
        metodosIterativos.setVisible(true);
        metodosIterativos.setSize(1024,768);
        metodosIterativos.setResizable(false);
        metodosIterativos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_regresarJacobiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jacobi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ayudaJacobi;
    private javax.swing.JButton ayudaLamba;
    private javax.swing.JButton botonCalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField iteracionesJacobi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton normaEuclidiana;
    private javax.swing.JRadioButton normaInfinito;
    private javax.swing.JButton regresarJacobi;
    private javax.swing.JTextField toleranciaJacobi;
    // End of variables declaration//GEN-END:variables
}
