/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author carlosruiz
 */
public class MetodosIterativos extends javax.swing.JFrame {

    /**
     * Creates new form MetodosIterativos
     */
    public MetodosIterativos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonJacobi = new javax.swing.JButton();
        botonGaussSeidel = new javax.swing.JButton();
        botonMiMatrizIterativa = new javax.swing.JButton();
        regresarMetodosIterativos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botonJacobi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonJacobi.png"))); // NOI18N
        botonJacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJacobiActionPerformed(evt);
            }
        });
        getContentPane().add(botonJacobi);
        botonJacobi.setBounds(310, 220, 430, 120);

        botonGaussSeidel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonGaussSeidel.png"))); // NOI18N
        botonGaussSeidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGaussSeidelActionPerformed(evt);
            }
        });
        getContentPane().add(botonGaussSeidel);
        botonGaussSeidel.setBounds(310, 390, 430, 120);

        botonMiMatrizIterativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonMiMatrizIterativa.png"))); // NOI18N
        botonMiMatrizIterativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMiMatrizIterativaActionPerformed(evt);
            }
        });
        getContentPane().add(botonMiMatrizIterativa);
        botonMiMatrizIterativa.setBounds(310, 560, 430, 110);

        regresarMetodosIterativos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        regresarMetodosIterativos.setToolTipText("");
        regresarMetodosIterativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarMetodosIterativosActionPerformed(evt);
            }
        });
        getContentPane().add(regresarMetodosIterativos);
        regresarMetodosIterativos.setBounds(50, 60, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MetodosIterativos.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJacobiActionPerformed
        // TODO add your handling code here:
        Jacobi jacobi = new Jacobi();
        jacobi.setVisible(true);
        jacobi.setSize(1024,768);
        jacobi.setResizable(false);
        jacobi.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonJacobiActionPerformed

    private void regresarMetodosIterativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarMetodosIterativosActionPerformed
        // TODO add your handling code here:
        SistemasEcuaciones se = new SistemasEcuaciones();
        se.setVisible(true);
        se.setSize(1024,768);
        se.setResizable(false);
        se.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_regresarMetodosIterativosActionPerformed

    private void botonMiMatrizIterativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMiMatrizIterativaActionPerformed
        // TODO add your handling code here:
        MiMatrizIterativa miMatriz = new MiMatrizIterativa();
        miMatriz.setVisible(true);
        miMatriz.setSize(1024,768);
        miMatriz.setResizable(false);
        miMatriz.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonMiMatrizIterativaActionPerformed

    private void botonGaussSeidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGaussSeidelActionPerformed
        // TODO add your handling code here:
        GaussSeidel gaussSeidel = new GaussSeidel();
        gaussSeidel.setVisible(true);
        gaussSeidel.setSize(1024,768);
        gaussSeidel.setResizable(false);
        gaussSeidel.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonGaussSeidelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGaussSeidel;
    private javax.swing.JButton botonJacobi;
    private javax.swing.JButton botonMiMatrizIterativa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regresarMetodosIterativos;
    // End of variables declaration//GEN-END:variables
}
