/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import practicaanalisis.Metodos2;

/**
 *
 * @author carlosruiz
 */
public class MiMatrizIterativa extends javax.swing.JFrame {

    /**
     * Creates new form MiMatrizIterativa
     */
    public MiMatrizIterativa() {
        initComponents();
        jTextField1.setText(String.valueOf(Metodos2.tam));
        if(Metodos2.tam != 0){
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                Metodos2.a,
                new String [Metodos2.tam]
            ));
            Double[][] matrizB = new Double[Metodos2.tam][1];
            for(int i=0; i<matrizB.length; i++){
                matrizB[i][0] = Metodos2.b[i];
            }
            jTable2.setModel(new javax.swing.table.DefaultTableModel(
                matrizB,
                new String [1]
            ));
            
            Double[][] matrizX = new Double[1][Metodos2.tam];
            String[] titulos = new String[Metodos2.tam];
            for(int i=0; i<Metodos2.tam; i++){
                titulos[i] = "X"+(i+1);
                matrizX[0][i] = Metodos2.x[i];
            }
            jTable3.setModel(new javax.swing.table.DefaultTableModel(
                matrizX,
                titulos
            ));
            
        }else{
            jTable1.setVisible(false);
            jTable2.setVisible(false);
            jTable3.setVisible(false);  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        actualizarN = new javax.swing.JButton();
        regresarMiMatriz = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(360, 135, 320, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setTableHeader(null);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 230, 810, 250);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setTableHeader(null);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(850, 230, 120, 250);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 540, 960, 90);

        actualizarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonActualizarN.png"))); // NOI18N
        actualizarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarNActionPerformed(evt);
            }
        });
        getContentPane().add(actualizarN);
        actualizarN.setBounds(690, 140, 150, 40);

        regresarMiMatriz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        regresarMiMatriz.setToolTipText("");
        regresarMiMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarMiMatrizActionPerformed(evt);
            }
        });
        getContentPane().add(regresarMiMatriz);
        regresarMiMatriz.setBounds(80, 30, 80, 80);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GuardarBoton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 650, 370, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MiMatrizIterativa.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMiMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarMiMatrizActionPerformed
        // TODO add your handling code here:
        MetodosIterativos metodosIterativos = new MetodosIterativos();
        metodosIterativos.setVisible(true);
        metodosIterativos.setSize(1024,768);
        metodosIterativos.setResizable(false);
        metodosIterativos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_regresarMiMatrizActionPerformed

    private void actualizarNActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        int n = Integer.parseInt(jTextField1.getText());
        //Metodos2.tam = n;
        if(n > 0){
        
        jTable1.setVisible(true);
        jTable2.setVisible(true);
        jTable3.setVisible(true);
        Double[][] matrizA = new Double[n][n];
        for(int i=0; i<matrizA.length; i++){
            for(int j=0; j<matrizA[i].length; j++){
                matrizA[i][j] = null;
            }
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matrizA,
            new String [n]
        ));
        
        Double[][] matrizB = new Double[n][1];
        for(int i=0; i<matrizB.length; i++){
            matrizB[i][0] = null;
        }
        //System.out.println(Arrays.toString(matrizB));
        //System.out.println(Arrays.toString(matrizB[0]));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            matrizB,
            new String [1]
        ));
        Double[][] matrizX = new Double[1][n];
        String[] titulos = new String[n];
        for(int i=0; i<n; i++){
            matrizX[0][i] = null;
            titulos[i] = "X"+(i+1);
        }
        //System.out.println(Arrays.toString(matrizB));
        //System.out.println(Arrays.toString(matrizB[0]));
        
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            matrizX,
            titulos
        ));
        }else{
            JOptionPane.showMessageDialog(rootPane, "Recuerde que el valor de N debe ser mayor a cero");
        }
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*
        Metodos2.tam = 3;
        //Metodos2.a = {};
        Metodos2.b = new Double[3];
        //Double[] tb = {-25.0,82.0,75.0,-43.0};
        Double[] tb = {-23.0,5.0,34.0};
        Metodos2.b = tb;
        //Double[][] ta = {{7.0,2.0,-3.0,4.0},{5.0,-1.0,14.0,-1.0},{1.0,9.0,-7.0,13.0},{-12.0,13.0,-8.0,-4.0}};
        //Double[][] ta = {{-7.0,0.0,-3.0,4.0},{5.0,0.0,14.0,-1.0},{1.0,0.0,-7.0,13.0},{-12.0,0.0,-8.0,-4.0}};
        //Double[][] ta = {{45.0,13.0,-4.0, 8.0},{-5.0,-28.0,4.0,-14.0},{9.0,15.0,63.0,-7.0},{2.0,3.0,-8.0,-42.0}};
        Double[][] ta = {{13.0,-4.0,-9.0},{3.0,-7.0,4.0},{-4.0,15.0,-16.0}};
        Metodos2.a = ta;
        
        Metodos2.x = new Double[3];
        //Double[] tx = {2.0,2.0,2.0,2.0};
        Double[] tx = {1.0,1.0,1.0};
        Metodos2.x = tx;
        */
        Metodos2.tam = Integer.parseInt(jTextField1.getText());
        Metodos2.a = getTableData(jTable1);
        Double[][] arregloB = getTableData(jTable2);
        Double[] matrizB = new Double[arregloB.length];
        for(int i=0; i < matrizB.length; i++){
            matrizB[i] = arregloB[i][0];
        }
        Metodos2.b = matrizB;
        
        Double[][] arregloX = getTableData(jTable3);
        Double[] matrizX = new Double[arregloX[0].length];
        for(int i=0; i < matrizX.length; i++){
            matrizX[i] = arregloX[0][i];
        }
        Metodos2.x = matrizX;
        
        
        //System.out.println(Arrays.toString(Metodos2.x));
        JOptionPane.showMessageDialog(rootPane, "Matriz guardada exitosamente");
    }//GEN-LAST:event_jButton1ActionPerformed

 
    public static Double[][] getTableData (JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        Double[][] tableData = new Double[nRow][nCol];
        for (int i = 0 ; i < nRow ; i++){
            for (int j = 0 ; j < nCol ; j++){
                System.out.println(dtm.getValueAt(i,j));
                if (dtm.getValueAt(i,j) == null || dtm.getValueAt(i,j).toString().replaceAll("\\s","").equals("")){
                    tableData[i][j] = 0.0;
                }else{
                    tableData[i][j] = Double.parseDouble(dtm.getValueAt(i,j).toString());
                }
                //tableData[i][j] = Double.parseDouble(dtm.getValueAt(i,j).toString());
            }
        }
        return tableData;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton regresarMiMatriz;
    // End of variables declaration//GEN-END:variables
}
