/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author pedrosalzedo
 */
public class Newton extends javax.swing.JFrame {

    /**
     * Creates new form Newton
     */
    public Newton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        iteracionesNewton = new javax.swing.JTextField();
        toleranciaNewton = new javax.swing.JTextField();
        xInicialNewton = new javax.swing.JTextField();
        errorABSNewton = new javax.swing.JRadioButton();
        errorRelNewton = new javax.swing.JRadioButton();
        botonRegresarNewton = new javax.swing.JButton();
        botonAyudaNewton = new javax.swing.JButton();
        calcularNewton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        iteracionesNewton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        iteracionesNewton.setSize(new java.awt.Dimension(300, 50));
        getContentPane().add(iteracionesNewton);
        iteracionesNewton.setBounds(380, 310, 300, 50);

        toleranciaNewton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        toleranciaNewton.setSize(new java.awt.Dimension(300, 50));
        getContentPane().add(toleranciaNewton);
        toleranciaNewton.setBounds(380, 400, 300, 50);

        xInicialNewton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        xInicialNewton.setSize(new java.awt.Dimension(300, 50));
        getContentPane().add(xInicialNewton);
        xInicialNewton.setBounds(380, 220, 300, 50);

        buttonGroup1.add(errorABSNewton);
        errorABSNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorABSNewtonActionPerformed(evt);
            }
        });
        getContentPane().add(errorABSNewton);
        errorABSNewton.setBounds(430, 520, 28, 23);

        buttonGroup1.add(errorRelNewton);
        errorRelNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorRelNewtonActionPerformed(evt);
            }
        });
        getContentPane().add(errorRelNewton);
        errorRelNewton.setBounds(810, 520, 28, 23);

        botonRegresarNewton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresarNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarNewtonActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarNewton);
        botonRegresarNewton.setBounds(80, 83, 80, 80);

        botonAyudaNewton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Ayuda.png"))); // NOI18N
        botonAyudaNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaNewtonActionPerformed(evt);
            }
        });
        getContentPane().add(botonAyudaNewton);
        botonAyudaNewton.setBounds(870, 70, 110, 110);

        calcularNewton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalcularBoton.png"))); // NOI18N
        calcularNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularNewtonActionPerformed(evt);
            }
        });
        getContentPane().add(calcularNewton);
        calcularNewton.setBounds(300, 640, 380, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Newton.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarNewtonActionPerformed
        // TODO add your handling code here:
        Abierto abiertos = new Abierto();
        abiertos.setVisible(true);
        abiertos.setSize(1024,768);
        abiertos.setResizable(false);
        abiertos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarNewtonActionPerformed

    private void botonAyudaNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaNewtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, null, "AYUDA - Newton", HEIGHT, new javax.swing.ImageIcon(getClass().getResource("/imagenes/Newton Ayuda.png")));
    }//GEN-LAST:event_botonAyudaNewtonActionPerformed

    private void errorABSNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorABSNewtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorABSNewtonActionPerformed

    private void errorRelNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorRelNewtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorRelNewtonActionPerformed

    private void calcularNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularNewtonActionPerformed
        // TODO add your handling code here:
        ResultadosNewton Rnewton = new ResultadosNewton();
        Rnewton.setVisible(true);
        Rnewton.setSize(1024,768);
        Rnewton.setResizable(false);
        Rnewton.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_calcularNewtonActionPerformed

    private void groupButton(){
        ButtonGroup bgroup = new ButtonGroup();
        
        bgroup.add(errorABSNewton);
        bgroup.add(errorRelNewton);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAyudaNewton;
    private javax.swing.JButton botonRegresarNewton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcularNewton;
    private javax.swing.JRadioButton errorABSNewton;
    private javax.swing.JRadioButton errorRelNewton;
    private javax.swing.JTextField iteracionesNewton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField toleranciaNewton;
    private javax.swing.JTextField xInicialNewton;
    // End of variables declaration//GEN-END:variables
}
