/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import practicaanalisis.Funcion;
import static practicaanalisis.Funcion.callFunction;
import practicaanalisis.Metodos;

/**
 *
 * @author pedrosalzedo
 */
public class PuntoFijo extends javax.swing.JFrame {
    private static java.text.DecimalFormat sf = new java.text.DecimalFormat("0.#E0");

    /**
     * Creates new form PuntoFijo
     */
    public PuntoFijo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        xInicialPuntoFijo = new javax.swing.JTextField();
        iteracionesPuntoFijo = new javax.swing.JTextField();
        toleranciaPuntoFijo = new javax.swing.JTextField();
        errorABSPuntoFijo = new javax.swing.JRadioButton();
        errorRelPuntoFijo = new javax.swing.JRadioButton();
        botonRegresarPuntoFijo = new javax.swing.JButton();
        ayudaPuntoFijo = new javax.swing.JButton();
        calcularPuntoFijo = new javax.swing.JButton();
        funcionesPuntoFijo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        xInicialPuntoFijo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(xInicialPuntoFijo);
        xInicialPuntoFijo.setBounds(370, 234, 460, 50);

        iteracionesPuntoFijo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(iteracionesPuntoFijo);
        iteracionesPuntoFijo.setBounds(370, 310, 460, 50);

        toleranciaPuntoFijo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        toleranciaPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toleranciaPuntoFijoActionPerformed(evt);
            }
        });
        getContentPane().add(toleranciaPuntoFijo);
        toleranciaPuntoFijo.setBounds(370, 410, 460, 50);

        buttonGroup1.add(errorABSPuntoFijo);
        errorABSPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorABSPuntoFijoActionPerformed(evt);
            }
        });
        getContentPane().add(errorABSPuntoFijo);
        errorABSPuntoFijo.setBounds(430, 520, 28, 23);

        buttonGroup1.add(errorRelPuntoFijo);
        errorRelPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorRelPuntoFijoActionPerformed(evt);
            }
        });
        getContentPane().add(errorRelPuntoFijo);
        errorRelPuntoFijo.setBounds(840, 520, 28, 23);

        botonRegresarPuntoFijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresarPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarPuntoFijoActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarPuntoFijo);
        botonRegresarPuntoFijo.setBounds(160, 70, 80, 80);

        ayudaPuntoFijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Ayuda.png"))); // NOI18N
        ayudaPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaPuntoFijoActionPerformed(evt);
            }
        });
        getContentPane().add(ayudaPuntoFijo);
        ayudaPuntoFijo.setBounds(790, 60, 110, 110);

        calcularPuntoFijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalcularBoton.png"))); // NOI18N
        calcularPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularPuntoFijoActionPerformed(evt);
            }
        });
        getContentPane().add(calcularPuntoFijo);
        calcularPuntoFijo.setBounds(570, 597, 300, 90);

        funcionesPuntoFijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonMisFunciones.png"))); // NOI18N
        funcionesPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionesPuntoFijoActionPerformed(evt);
            }
        });
        getContentPane().add(funcionesPuntoFijo);
        funcionesPuntoFijo.setBounds(160, 600, 310, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PuntoFijo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void errorABSPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorABSPuntoFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorABSPuntoFijoActionPerformed

    private void errorRelPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorRelPuntoFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorRelPuntoFijoActionPerformed

    private void calcularPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularPuntoFijoActionPerformed
        // TODO add your handling code here:
        double x0 = 0;
        int iter = 0;
        double tol = 0;
        boolean camposCorrectos = true;
        
        try{
            x0 = Double.parseDouble(xInicialPuntoFijo.getText());
            iter = Integer.parseInt(iteracionesPuntoFijo.getText());
            tol = Double.parseDouble(toleranciaPuntoFijo.getText());
        }catch(Exception e){
            camposCorrectos = false;
        }
        
        if(iter <= 0 && tol <= 0){
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese información correcta a los campos, como un número mayor que cero para iteraciones y número mayor de cero para la tolerancia");
            camposCorrectos = false;
        }else if(iter <= 0){    
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un número mayor que cero para iteraciones");
            camposCorrectos = false;
        } else if(tol <= 0){
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un número mayor de cero para la tolerancia");
            camposCorrectos = false;
        } else{
            camposCorrectos = true;
        }
        
        errorABSPuntoFijo.setActionCommand("0");
        errorRelPuntoFijo.setActionCommand("1");
        int err = 0;
        try{
            err = Integer.parseInt(buttonGroup1.getSelection().getActionCommand());
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccionar el tipo de error para trabajar");
            camposCorrectos = false;
        }
        
        if (camposCorrectos){
            if(!"".equals(Funcion.g) && !"".equals(Funcion.f)){
                String mensaje = "";
                boolean correct = false;
                Double[][] data = null;

                double fx0 = callFunction("f", x0);

                if(fx0 == 0){
                    mensaje = x0 + " es una raíz ";
                }else if (iter <= 0){
                    mensaje = "El numero de iteraciones debe de ser mayor a cero";
                }else if(tol <= 0){
                    mensaje = "La tolerancia debe de ser mayor a cero";
                }else{
                    Metodos.PuntoFijo(x0, iter, tol, err);
                    //Resultados
                    data = Metodos.data;
                    Object[][] newData = formatearData(data);
                    mensaje = Metodos.mens;

                    ResultadosPuntoFijo RpuntoFijo = new ResultadosPuntoFijo(x0, tol, iter, newData, mensaje);
                    RpuntoFijo.setVisible(true);
                    RpuntoFijo.setSize(1024,768);
                    RpuntoFijo.setResizable(false);
                    RpuntoFijo.setLocationRelativeTo(null);
                    dispose();
                    correct = true;
                    }
                if (!correct){
                    JOptionPane.showMessageDialog(rootPane, mensaje);            
                }
            }else{
            JOptionPane.showMessageDialog(rootPane, "Por favor ingresar una función F(x) y G(x) válida para ejecutar el método");
            }
        }
    }//GEN-LAST:event_calcularPuntoFijoActionPerformed

    private void botonRegresarPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarPuntoFijoActionPerformed
        // TODO add your handling code here:
        Abierto abiertos = new Abierto();
        abiertos.setVisible(true);
        abiertos.setSize(1024,768);
        abiertos.setResizable(false);
        abiertos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarPuntoFijoActionPerformed

    private void ayudaPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaPuntoFijoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, null, "AYUDA - Punto Fijo", HEIGHT, new javax.swing.ImageIcon(getClass().getResource("/imagenes/Punto Fijo Ayuda.png")));
    }//GEN-LAST:event_ayudaPuntoFijoActionPerformed

    private void funcionesPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionesPuntoFijoActionPerformed
        // TODO add your handling code here:
        Funciones func = new Funciones("puntofijo");
        func.setVisible(true);
        func.setSize(1024,768);
        func.setResizable(false);
        func.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_funcionesPuntoFijoActionPerformed

    private void toleranciaPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toleranciaPuntoFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toleranciaPuntoFijoActionPerformed

    private void groupButton(){
        ButtonGroup bgroup = new ButtonGroup();
        
        bgroup.add(errorABSPuntoFijo);
        bgroup.add(errorRelPuntoFijo);
    }
    
    private Object[][] formatearData(Double[][] data) {
        Object[][] newData = new Object[data.length][];
        for(int i = 0; i < data.length; i++){
            newData[i] = new Object[4];
            newData[i][0] = data[i][0].intValue();
            newData[i][1] = data[i][1];
            newData[i][2] = sf.format(data[i][2]);
            newData[i][3] = sf.format(data[i][3]);           
            
        }
        return newData;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ayudaPuntoFijo;
    private javax.swing.JButton botonRegresarPuntoFijo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcularPuntoFijo;
    private javax.swing.JRadioButton errorABSPuntoFijo;
    private javax.swing.JRadioButton errorRelPuntoFijo;
    private javax.swing.JButton funcionesPuntoFijo;
    private javax.swing.JTextField iteracionesPuntoFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField toleranciaPuntoFijo;
    private javax.swing.JTextField xInicialPuntoFijo;
    // End of variables declaration//GEN-END:variables
}
