/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;
import practicaanalisis.Metodos;
import practicaanalisis.Funcion;

/**
 *
 * @author carlosruiz
 */
public class RaicesMultiples extends javax.swing.JFrame{
    private static java.text.DecimalFormat sf = new java.text.DecimalFormat("0.#E0");
    

    /**
     * Creates new form RaicesMultiples
     */
    public RaicesMultiples() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        x0RaicesMultiples = new javax.swing.JTextField();
        iteracionesRaicesMultiples = new javax.swing.JTextField();
        toleranciaRaicesMultiples = new javax.swing.JTextField();
        botonRegresarRaicesMultiples = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        ayudaRaices = new javax.swing.JButton();
        botonMisFunciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        x0RaicesMultiples.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(x0RaicesMultiples);
        x0RaicesMultiples.setBounds(370, 225, 480, 45);

        iteracionesRaicesMultiples.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(iteracionesRaicesMultiples);
        iteracionesRaicesMultiples.setBounds(370, 315, 480, 40);

        toleranciaRaicesMultiples.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(toleranciaRaicesMultiples);
        toleranciaRaicesMultiples.setBounds(370, 415, 480, 45);

        botonRegresarRaicesMultiples.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresarRaicesMultiples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarRaicesMultiplesActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarRaicesMultiples);
        botonRegresarRaicesMultiples.setBounds(60, 50, 80, 80);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalcularBoton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 610, 380, 100);

        buttonGroup1.add(jRadioButton1);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(420, 520, 30, 23);

        buttonGroup1.add(jRadioButton2);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(800, 520, 28, 23);

        ayudaRaices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Ayuda.png"))); // NOI18N
        ayudaRaices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaRaicesActionPerformed(evt);
            }
        });
        getContentPane().add(ayudaRaices);
        ayudaRaices.setBounds(890, 40, 110, 110);

        botonMisFunciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonMisFunciones.png"))); // NOI18N
        botonMisFunciones.setToolTipText("");
        botonMisFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMisFuncionesActionPerformed(evt);
            }
        });
        getContentPane().add(botonMisFunciones);
        botonMisFunciones.setBounds(190, 620, 300, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RaicesMultiples.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarRaicesMultiplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarRaicesMultiplesActionPerformed
        // TODO add your handling code here:
        Abierto abierto = new Abierto();
        abierto.setVisible(true);
        abierto.setSize(1024,768);
        abierto.setResizable(false);
        abierto.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarRaicesMultiplesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        double x0 = 0;
        double tol = 0;
        int iter = 0;
        boolean camposCorrectos = true;
        
        try{
            x0 = Double.parseDouble(x0RaicesMultiples.getText());
            tol = Double.parseDouble(toleranciaRaicesMultiples.getText());
            iter = Integer.parseInt(iteracionesRaicesMultiples.getText());
        }catch(Exception e){
            camposCorrectos = false;
        }
        
        if(iter <= 0 && tol <= 0){
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese información correcta a los campos, como un número mayor que cero para iteraciones y número mayor de cero para la tolerancia");
            camposCorrectos = false;
        }else if(iter <= 0){    
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un número mayor que cero para iteraciones");
            camposCorrectos = false;
        } else if(tol <= 0){
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un número mayor de cero para la tolerancia");
            camposCorrectos = false;
        } else{
            camposCorrectos = true;
        }
                
        jRadioButton1.setActionCommand("0");
        jRadioButton2.setActionCommand("1");
        
        int err = 0;
        
        try{
            err = Integer.parseInt(buttonGroup1.getSelection().getActionCommand());
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccionar el tipo de error para trabajar");
            camposCorrectos = false;
        }
        
        
        if(camposCorrectos){
            if(!"".equals(Funcion.f) && !"".equals(Funcion.df) && !"".equals(Funcion.ddf)){
                String mensaje = "";
                boolean correct = false;
                Double[][] data = null;

                if (iter <= 0){
                    mensaje = "El numero de iteraciones debe de ser mayor a cero";
                }else if(tol <= 0){
                    mensaje = "La tolerancia debe de ser mayor a cero";
                }else {
                    Metodos.raicesMultiples(x0, iter, tol, err);
                    //Resultados
                    data = Metodos.data;
                    Object[][] newData = formatearData(data);
                    mensaje = Metodos.mens;


                    ResultadosRaicesMultiples resultadosRaicesMultiples = new ResultadosRaicesMultiples(x0,tol, iter, newData, mensaje);
                    resultadosRaicesMultiples.setVisible(true);
                    resultadosRaicesMultiples.setSize(1024,768);
                    resultadosRaicesMultiples.setResizable(false);
                    resultadosRaicesMultiples.setLocationRelativeTo(null);
                    dispose();
                }
                if (!correct){
                    JOptionPane.showMessageDialog(rootPane, mensaje);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Por favor ingresar una función F(x) y G(x) válida para ejecutar el método");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ayudaRaicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaRaicesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, null, "AYUDA - Raices Múltiples", HEIGHT, new javax.swing.ImageIcon(getClass().getResource("/imagenes/RaicesAyuda.png")));
    }//GEN-LAST:event_ayudaRaicesActionPerformed

    private void botonMisFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMisFuncionesActionPerformed
        // TODO add your handling code here:
        Funciones func = new Funciones("raicesmultiples");
        func.setVisible(true);
        func.setSize(1024,768);
        func.setResizable(false);
        func.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonMisFuncionesActionPerformed
    
    private Object[][] formatearData(Double[][] data) {
        Object[][] newData = new Object[data.length][];
        for(int i = 0; i < data.length; i++){
            newData[i] = new Object[6];
            newData[i][0] = data[i][0].intValue();
            newData[i][1] = data[i][1];
            newData[i][2] = sf.format(data[i][2]);
            newData[i][3] = sf.format(data[i][3]);  
            newData[i][4] = sf.format(data[i][4]);
            newData[i][5] = sf.format(data[i][5]); 
            
        }
        return newData;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ayudaRaices;
    private javax.swing.JButton botonMisFunciones;
    private javax.swing.JButton botonRegresarRaicesMultiples;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField iteracionesRaicesMultiples;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField toleranciaRaicesMultiples;
    private javax.swing.JTextField x0RaicesMultiples;
    // End of variables declaration//GEN-END:variables
}
