/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author carlosruiz
 */
public class ResultadosRaicesMultiples extends javax.swing.JFrame {

    /**
     * Creates new form ResultadosRaicesMultiples
     */
    public ResultadosRaicesMultiples(double x0, double tol, int iter, Object[][] dat, String res) {
        initComponents();
        tableRaicesMultiples.setModel(new javax.swing.table.DefaultTableModel(
            dat,
            new String [] {
                "n", "Xn", "f(Xm)", "f'(Xm)", "f''(Xm)", "Error"
            }
        ));
        textResult.setText(res);
        x0RaicesMultiples.setText(String.valueOf(x0));
        iteracionesRaicesMultiples.setText(String.valueOf(iter));
        toleranciaRaicesMultiples.setText(String.valueOf(tol));
        x0RaicesMultiples.setEditable(false);
        iteracionesRaicesMultiples.setEditable(false);
        toleranciaRaicesMultiples.setEditable(false);
        textResult.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresarResultadosRaicesMultiples = new javax.swing.JButton();
        x0RaicesMultiples = new javax.swing.JTextField();
        iteracionesRaicesMultiples = new javax.swing.JTextField();
        toleranciaRaicesMultiples = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRaicesMultiples = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textResult = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botonRegresarResultadosRaicesMultiples.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresarResultadosRaicesMultiples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarResultadosRaicesMultiplesActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarResultadosRaicesMultiples);
        botonRegresarResultadosRaicesMultiples.setBounds(50, 30, 80, 80);

        x0RaicesMultiples.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(x0RaicesMultiples);
        x0RaicesMultiples.setBounds(240, 105, 680, 45);

        iteracionesRaicesMultiples.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(iteracionesRaicesMultiples);
        iteracionesRaicesMultiples.setBounds(370, 160, 140, 45);

        toleranciaRaicesMultiples.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(toleranciaRaicesMultiples);
        toleranciaRaicesMultiples.setBounds(710, 160, 210, 45);

        tableRaicesMultiples.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tableRaicesMultiples.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableRaicesMultiples.setRowHeight(30);
        jScrollPane1.setViewportView(tableRaicesMultiples);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 930, 290);

        textResult.setColumns(20);
        textResult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textResult.setRows(5);
        jScrollPane2.setViewportView(textResult);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 610, 930, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ResultadoRaicesMultiples.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarResultadosRaicesMultiplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarResultadosRaicesMultiplesActionPerformed
        // TODO add your handling code here:
        RaicesMultiples raicesMultiples = new RaicesMultiples();
        raicesMultiples.setVisible(true);
        raicesMultiples.setSize(1024,768);
        raicesMultiples.setResizable(false);
        raicesMultiples.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarResultadosRaicesMultiplesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarResultadosRaicesMultiples;
    private javax.swing.JTextField iteracionesRaicesMultiples;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableRaicesMultiples;
    private javax.swing.JTextArea textResult;
    private javax.swing.JTextField toleranciaRaicesMultiples;
    private javax.swing.JTextField x0RaicesMultiples;
    // End of variables declaration//GEN-END:variables
}
