/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import practicaanalisis.Metodos2;

/**
 *
 * @author carlosruiz
 */
public class ResultadosMetodosDirectos extends javax.swing.JFrame {

    public static String resultado;
    public static String matrizFinal;
    public static String etapas;
    
    /**
     * Creates new form PivoteoParcial
     */
    public ResultadosMetodosDirectos(String res, String matriz, String eta) {
        
        initComponents();
        resultado = res;
        matrizFinal = matriz;
        etapas = eta;
        jTextArea1.setText(resultado);
        
        //System.out.println("RESULTADOOO");
        //System.out.println(matrizFinal);
        matrizFinal = matrizFinal.replace("[ ", "");
        matrizFinal = matrizFinal.replace("[", "");
        matrizFinal = matrizFinal.replace("]", "");
        matrizFinal = matrizFinal.replace("\n", "");
        matrizFinal =  matrizFinal.replaceAll("\\s+"," ");
        matrizFinal = matrizFinal.replace(" ", "!");
        
        //matrizFinal = matrizFinal.replace(".!", ".0!");
        
        /*matrizFinal = matrizFinal.replace("[", "");
        matrizFinal = matrizFinal.replace("]", "");
        matrizFinal = matrizFinal.replace("\n", "");
        matrizFinal = matrizFinal.replace("    ", "!");
        matrizFinal = matrizFinal.replace("  ", "!");
        matrizFinal = matrizFinal.replace("! ", "!");*/
        //System.out.println(matrizFinal);
        String[] arrMatrizFinal = matrizFinal.split("!"); 
        
        List<String> list = new ArrayList<String>(Arrays.asList(arrMatrizFinal));
        list.remove("");
        arrMatrizFinal = list.toArray(new String[0]);
        
        Double[][] dMatrizFinal = new Double[Metodos2.tam][Metodos2.tam+1];
        int cont = 0;
        for (int i = 0; i < Metodos2.tam; i++) {
            for (int j = 0; j < Metodos2.tam+1; j++) {
                dMatrizFinal[i][j] = Double.parseDouble(arrMatrizFinal[cont]);
                cont++;
            }
        }
        //System.out.println("dMatrizFinal");
        //System.out.println(dMatrizFinal);
        
        TablaPivoteoParcial.setModel(new javax.swing.table.DefaultTableModel(
                dMatrizFinal,
                new String [Metodos2.tam]
            ));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarResultadosMetodos = new javax.swing.JButton();
        verEtapasPivoteoParcial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPivoteoParcial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        regresarResultadosMetodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        regresarResultadosMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarResultadosMetodosActionPerformed(evt);
            }
        });
        getContentPane().add(regresarResultadosMetodos);
        regresarResultadosMetodos.setBounds(50, 30, 80, 80);

        verEtapasPivoteoParcial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonVerEtapas.png"))); // NOI18N
        verEtapasPivoteoParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEtapasPivoteoParcialActionPerformed(evt);
            }
        });
        getContentPane().add(verEtapasPivoteoParcial);
        verEtapasPivoteoParcial.setBounds(700, 660, 300, 90);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 90, 720, 120);

        TablaPivoteoParcial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaPivoteoParcial.setTableHeader(null);
        TablaPivoteoParcial.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(TablaPivoteoParcial);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 270, 980, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ResultadoMatriz.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarResultadosMetodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarResultadosMetodosActionPerformed
        // TODO add your handling code here:
        MetodosDirectos metodosDirectos = new MetodosDirectos();
        metodosDirectos.setVisible(true);
        metodosDirectos.setSize(1024,768);
        metodosDirectos.setResizable(false);
        metodosDirectos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_regresarResultadosMetodosActionPerformed

    private void verEtapasPivoteoParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEtapasPivoteoParcialActionPerformed
        // TODO add your handling code here:
        
        
        EtapasMetodosDirectos etapasMetodosDirectos = new EtapasMetodosDirectos(resultado, matrizFinal, etapas);
        etapasMetodosDirectos.setVisible(true);
        etapasMetodosDirectos.setSize(1024,768);
        etapasMetodosDirectos.setResizable(false);
        etapasMetodosDirectos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_verEtapasPivoteoParcialActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPivoteoParcial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton regresarResultadosMetodos;
    private javax.swing.JButton verEtapasPivoteoParcial;
    // End of variables declaration//GEN-END:variables
}
