/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import practicaanalisis.Metodos2;

/**
 *
 * @author carlosruiz
 */
public class ResultadosFactorizacionLU extends javax.swing.JFrame {

    public static String resultado;
    public static String matrizFinalL;
    public static String matrizFinalU;
    public static String etapas;
    public static String matrizInv;
    
    /**
     * Creates new form ResultadosMetodosIterativos
     */
    public ResultadosFactorizacionLU(String res, String matrizL, String matrizU, String eta) {
        initComponents();
        System.out.println("MATRIZ L");
        System.out.println(matrizL);
        resultado = res;
        matrizFinalL = matrizL;
        matrizFinalU = matrizU;
        etapas = eta;
        jTextArea1.setText(resultado);
        
        matrizFinalL = matrizFinalL.replace("[ ", "");
        matrizFinalL = matrizFinalL.replace("[", "");
        matrizFinalL = matrizFinalL.replace("]", "");
        matrizFinalL = matrizFinalL.replace("\n", "");
        matrizFinalL =  matrizFinalL.replaceAll("\\s+"," ");
        matrizFinalL = matrizFinalL.replace(" ", "!");
        
        matrizFinalU = matrizFinalU.replace("[ ", "");
        matrizFinalU = matrizFinalU.replace("[", "");
        matrizFinalU = matrizFinalU.replace("]", "");
        matrizFinalU = matrizFinalU.replace("\n", "");
        matrizFinalU =  matrizFinalU.replaceAll("\\s+"," ");
        matrizFinalU = matrizFinalU.replace(" ", "!");
        
        String[] arrMatrizFinalL = matrizFinalL.split("!");
        String[] arrMatrizFinalU = matrizFinalU.split("!");
        
        List<String> listL = new ArrayList<String>(Arrays.asList(arrMatrizFinalL));
        listL.remove("");
        arrMatrizFinalL = listL.toArray(new String[0]);
        
        List<String> listU = new ArrayList<String>(Arrays.asList(arrMatrizFinalU));
        listU.remove("");
        arrMatrizFinalU = listU.toArray(new String[0]);
        
        Double[][] dMatrizFinalL = new Double[Metodos2.tam][Metodos2.tam];
        Double[][] dMatrizFinalU = new Double[Metodos2.tam][Metodos2.tam];
        
        int contL = 0;
        for (int i = 0; i < Metodos2.tam; i++) {
            for (int j = 0; j < Metodos2.tam; j++) {
                dMatrizFinalL[i][j] = Double.parseDouble(arrMatrizFinalL[contL]);
                contL++;
            }
        }
        int contU = 0;
        for (int i = 0; i < Metodos2.tam; i++) {
            for (int j = 0; j < Metodos2.tam; j++) {
                dMatrizFinalU[i][j] = Double.parseDouble(arrMatrizFinalU[contU]);
                contU++;
            }
        }
        
        factorizacionL.setModel(new javax.swing.table.DefaultTableModel(
                dMatrizFinalL,
                new String [Metodos2.tam]
            ));
        factorizacionU.setModel(new javax.swing.table.DefaultTableModel(
                dMatrizFinalU,
                new String [Metodos2.tam]
            ));
        Double[][] ml = getTableData(factorizacionL);
        Double[][] mu = getTableData(factorizacionU);
        Metodos2.l = ml;
        Metodos2.u = mu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        botonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        factorizacionL = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        factorizacionU = new javax.swing.JTable();
        calcularInversa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar);
        botonRegresar.setBounds(70, 30, 80, 80);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 100, 550, 150);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonVerEtapas.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 675, 300, 80);

        factorizacionL.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        factorizacionL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        factorizacionL.setRowHeight(30);
        factorizacionL.setTableHeader(null);
        jScrollPane5.setViewportView(factorizacionL);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(30, 320, 454, 340);

        factorizacionU.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        factorizacionU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        factorizacionU.setRowHeight(30);
        factorizacionU.setTableHeader(null);
        jScrollPane6.setViewportView(factorizacionU);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(500, 320, 454, 340);

        calcularInversa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonCalcularInversa.png"))); // NOI18N
        calcularInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularInversaActionPerformed(evt);
            }
        });
        getContentPane().add(calcularInversa);
        calcularInversa.setBounds(360, 665, 340, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ResultadosLU.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        MetodosDirectos metodosDirectos = new MetodosDirectos();
        metodosDirectos.setVisible(true);
        metodosDirectos.setSize(1024,768);
        metodosDirectos.setResizable(false);
        metodosDirectos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EtapasMetodosDirectos etapasMetodosDirectos = new EtapasMetodosDirectos(resultado, matrizFinalL, matrizFinalU, etapas);
        etapasMetodosDirectos.setVisible(true);
        etapasMetodosDirectos.setSize(1024,768);
        etapasMetodosDirectos.setResizable(false);
        etapasMetodosDirectos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void calcularInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularInversaActionPerformed

        // TODO add your handling code here:
        
        //System.out.println(Arrays.deepToString(ml));
        Metodos2.matrizInversa(Metodos2.l, Metodos2.u, Metodos2.tam);
        try {
            String s = null;

            boolean error=false;
            while ((s = Metodos2.stdError.readLine()) != null) {
                JOptionPane.showMessageDialog(this,s,"Error",JOptionPane.ERROR_MESSAGE);
                error=true;
            } 
            if(!error){
                //Interpretar para obtener 3 cosas: matrizFinal(Pasar a Double[][]), Resultados de X(String) y etapas(String)
                String output = "";
                while ((s = Metodos2.stdOutput.readLine()) != null) {
                    //System.out.println(s);
                    output = output + (s + "\n");
                }

                String[] arrOutput = output.split("!");
                matrizInv = arrOutput[0];
                //System.out.println("SALIDA JAVA");
                //System.out.println(etapas);
                //System.out.println("--");
                //System.out.println(matrizFinal);
                //System.out.println("---");
                //System.out.println(resultado);
                //System.out.println("FIN SALIDA JAVA");


            }
        } catch (IOException ex) {
            Logger.getLogger(MetodosDirectos.class.getName()).log(Level.SEVERE, null, ex);
        }
        MatrizInversa matrizInversa = new MatrizInversa(matrizInv);
        matrizInversa.setVisible(true);
        matrizInversa.setSize(1024,768);
        matrizInversa.setResizable(false);
        matrizInversa.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_calcularInversaActionPerformed

    public static Double[][] getTableData (JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        Double[][] tableData = new Double[nRow][nCol];
        for (int i = 0 ; i < nRow ; i++){
            for (int j = 0 ; j < nCol ; j++){
                //System.out.println(dtm.getValueAt(i,j));
                if (dtm.getValueAt(i,j) == null || dtm.getValueAt(i,j).toString().replaceAll("\\s","").equals("")){
                    tableData[i][j] = 0.0;
                }else{
                    tableData[i][j] = Double.parseDouble(dtm.getValueAt(i,j).toString());
                }
                //tableData[i][j] = Double.parseDouble(dtm.getValueAt(i,j).toString());
            }
        }
        return tableData;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton calcularInversa;
    private javax.swing.JTable factorizacionL;
    private javax.swing.JTable factorizacionU;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
