/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Font;

/**
 *
 * @author pedrosalzedo
 */
public class ResultadosBusquedas extends javax.swing.JFrame {

    /**
     * Creates new form ResultadosBusquedas
     */
    public ResultadosBusquedas(double x0, double delta, int iter, Object[][] dat, String res) {
        initComponents();
        tableBusquedas.setModel(new javax.swing.table.DefaultTableModel(
            dat,
            new String [] {
                "n", "Xn", "FXn"
            }
        ));
        textResultado.setText(res);
        valorInicialBusquedas.setText(String.valueOf(x0));
        deltaBusquedas.setText(String.valueOf(delta));
        iteracionesBusquedas.setText(String.valueOf(iter));
        
        valorInicialBusquedas.setEditable(false);
        deltaBusquedas.setEditable(false);
        iteracionesBusquedas.setEditable(false);
        textResultado.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deltaBusquedas = new javax.swing.JTextField();
        iteracionesBusquedas = new javax.swing.JTextField();
        valorInicialBusquedas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBusquedas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textResultado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        deltaBusquedas.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(deltaBusquedas);
        deltaBusquedas.setBounds(265, 163, 220, 40);

        iteracionesBusquedas.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(iteracionesBusquedas);
        iteracionesBusquedas.setBounds(680, 112, 200, 40);

        valorInicialBusquedas.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(valorInicialBusquedas);
        valorInicialBusquedas.setBounds(265, 110, 220, 40);

        tableBusquedas.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tableBusquedas.getTableHeader().setFont(new Font("Lucida Grande", Font.ITALIC, 24));
        tableBusquedas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBusquedas.setRowHeight(30);
        jScrollPane1.setViewportView(tableBusquedas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 270, 940, 290);

        textResultado.setColumns(20);
        textResultado.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        textResultado.setRows(5);
        jScrollPane2.setViewportView(textResultado);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 640, 940, 90);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 30, 80, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ResultadosBusquedasIncrementales.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1020, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BusquedasIncr bi = new BusquedasIncr();
        bi.setVisible(true);
        bi.setSize(1024,768);
        bi.setResizable(false);
        bi.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deltaBusquedas;
    private javax.swing.JTextField iteracionesBusquedas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableBusquedas;
    private javax.swing.JTextArea textResultado;
    private javax.swing.JTextField valorInicialBusquedas;
    // End of variables declaration//GEN-END:variables
}
