/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author pedrosalzedo
 */
public class ResultadosNewton extends javax.swing.JFrame {

    /**
     * Creates new form ResultadosNewton
     */
    public ResultadosNewton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xInicialNewton = new javax.swing.JTextField();
        iteracionesNewton = new javax.swing.JTextField();
        toleranciaNewton = new javax.swing.JTextField();
        botonRegresarResultadosNewton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        xInicialNewton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        xInicialNewton.setSize(new java.awt.Dimension(240, 50));
        getContentPane().add(xInicialNewton);
        xInicialNewton.setBounds(240, 100, 240, 50);

        iteracionesNewton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(iteracionesNewton);
        iteracionesNewton.setBounds(360, 160, 120, 50);

        toleranciaNewton.setSize(new java.awt.Dimension(240, 50));
        getContentPane().add(toleranciaNewton);
        toleranciaNewton.setBounds(690, 160, 240, 50);

        botonRegresarResultadosNewton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresarResultadosNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarResultadosNewtonActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarResultadosNewton);
        botonRegresarResultadosNewton.setBounds(50, 40, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ResultadoNewton.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarResultadosNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarResultadosNewtonActionPerformed
        // TODO add your handling code here:
        Newton newton = new Newton();
        newton.setVisible(true);
        newton.setSize(1024,768);
        newton.setResizable(false);
        newton.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarResultadosNewtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadosNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadosNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadosNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadosNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadosNewton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarResultadosNewton;
    private javax.swing.JTextField iteracionesNewton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField toleranciaNewton;
    private javax.swing.JTextField xInicialNewton;
    // End of variables declaration//GEN-END:variables
}
