/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author carlosruiz
 */
public class ResultadosRaicesMultiples extends javax.swing.JFrame {

    /**
     * Creates new form ResultadosRaicesMultiples
     */
    public ResultadosRaicesMultiples() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresarResultadosRaicesMultiples = new javax.swing.JButton();
        x0RaicesMultiples = new javax.swing.JTextField();
        iteracionesRaicesMultiples = new javax.swing.JTextField();
        toleranciaRaicesMultiples = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botonRegresarResultadosRaicesMultiples.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresarResultadosRaicesMultiples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarResultadosRaicesMultiplesActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarResultadosRaicesMultiples);
        botonRegresarResultadosRaicesMultiples.setBounds(50, 30, 80, 80);

        x0RaicesMultiples.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        getContentPane().add(x0RaicesMultiples);
        x0RaicesMultiples.setBounds(240, 105, 680, 45);

        iteracionesRaicesMultiples.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        iteracionesRaicesMultiples.setSize(new java.awt.Dimension(140, 45));
        getContentPane().add(iteracionesRaicesMultiples);
        iteracionesRaicesMultiples.setBounds(370, 160, 140, 50);

        toleranciaRaicesMultiples.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        toleranciaRaicesMultiples.setSize(new java.awt.Dimension(210, 45));
        getContentPane().add(toleranciaRaicesMultiples);
        toleranciaRaicesMultiples.setBounds(710, 160, 210, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ResultadoRaicesMultiples.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarResultadosRaicesMultiplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarResultadosRaicesMultiplesActionPerformed
        // TODO add your handling code here:
        RaicesMultiples raicesMultiples = new RaicesMultiples();
        raicesMultiples.setVisible(true);
        raicesMultiples.setSize(1024,768);
        raicesMultiples.setResizable(false);
        raicesMultiples.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarResultadosRaicesMultiplesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadosRaicesMultiples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadosRaicesMultiples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadosRaicesMultiples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadosRaicesMultiples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadosRaicesMultiples().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarResultadosRaicesMultiples;
    private javax.swing.JTextField iteracionesRaicesMultiples;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField toleranciaRaicesMultiples;
    private javax.swing.JTextField x0RaicesMultiples;
    // End of variables declaration//GEN-END:variables
}
