/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author carlosruiz
 */
public class ResultadosSecante extends javax.swing.JFrame  {

    /**
     * Creates new form ResultadosSecante
     */
    public ResultadosSecante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x0Secante = new javax.swing.JTextField();
        iteracionesSecante = new javax.swing.JTextField();
        toleranciaSecante = new javax.swing.JTextField();
        botonRegresarResultadoSecante = new javax.swing.JButton();
        x1Secante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        x0Secante.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        x0Secante.setSize(new java.awt.Dimension(260, 45));
        getContentPane().add(x0Secante);
        x0Secante.setBounds(240, 110, 260, 50);

        iteracionesSecante.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        iteracionesSecante.setSize(new java.awt.Dimension(260, 45));
        getContentPane().add(iteracionesSecante);
        iteracionesSecante.setBounds(700, 110, 260, 45);

        toleranciaSecante.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        toleranciaSecante.setSize(new java.awt.Dimension(260, 45));
        getContentPane().add(toleranciaSecante);
        toleranciaSecante.setBounds(700, 160, 260, 45);

        botonRegresarResultadoSecante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonRegresarResultadoSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarResultadoSecanteActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarResultadoSecante);
        botonRegresarResultadoSecante.setBounds(160, 20, 80, 80);

        x1Secante.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        x1Secante.setSize(new java.awt.Dimension(260, 45));
        getContentPane().add(x1Secante);
        x1Secante.setBounds(240, 160, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ResultadoSecante.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarResultadoSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarResultadoSecanteActionPerformed
        // TODO add your handling code here:
        Secante secante = new Secante();
        secante.setVisible(true);
        secante.setSize(1024,768);
        secante.setResizable(false);
        secante.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonRegresarResultadoSecanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarResultadoSecante;
    private javax.swing.JTextField iteracionesSecante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField toleranciaSecante;
    private javax.swing.JTextField x0Secante;
    private javax.swing.JTextField x1Secante;
    // End of variables declaration//GEN-END:variables
}
