/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author carlosruiz
 */
public class SistemasEcuaciones extends javax.swing.JFrame {

    /**
     * Creates new form SistemasEcuaciones
     */
    public SistemasEcuaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarSistemasEcuaciones = new javax.swing.JButton();
        MetodosDirectos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        regresarSistemasEcuaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        regresarSistemasEcuaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarSistemasEcuacionesActionPerformed(evt);
            }
        });
        getContentPane().add(regresarSistemasEcuaciones);
        regresarSistemasEcuaciones.setBounds(70, 110, 80, 80);

        MetodosDirectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonMetodosDirectos.png"))); // NOI18N
        MetodosDirectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetodosDirectosActionPerformed(evt);
            }
        });
        getContentPane().add(MetodosDirectos);
        MetodosDirectos.setBounds(300, 350, 430, 120);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonMetodosIterativos.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 530, 430, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SistemasEcuaciones.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarSistemasEcuacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarSistemasEcuacionesActionPerformed
        // TODO add your handling code here:
        Temas temas = new Temas();
        temas.setVisible(true);
        temas.setSize(1024,768);
        temas.setResizable(false);
        temas.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_regresarSistemasEcuacionesActionPerformed

    private void MetodosDirectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetodosDirectosActionPerformed
        // TODO add your handling code here:
        MetodosDirectos metodosDirectos = new MetodosDirectos();
        metodosDirectos.setVisible(true);
        metodosDirectos.setSize(1024,768);
        metodosDirectos.setResizable(false);
        metodosDirectos.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_MetodosDirectosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MetodosDirectos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regresarSistemasEcuaciones;
    // End of variables declaration//GEN-END:variables
}
