/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Daniel Rendon M
 */
public class Temas extends javax.swing.JFrame {

    /**
     * Creates new form Temas
     */
    public Temas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonVolver = new javax.swing.JButton();
        botonEc1Var = new javax.swing.JButton();
        botonSisEcu = new javax.swing.JButton();
        botonInterp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Regresar.png"))); // NOI18N
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver);
        botonVolver.setBounds(30, 50, 80, 80);

        botonEc1Var.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Temas 1 .png"))); // NOI18N
        botonEc1Var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEc1VarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEc1Var);
        botonEc1Var.setBounds(310, 230, 420, 120);

        botonSisEcu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Temas 2.png"))); // NOI18N
        botonSisEcu.setToolTipText("");
        botonSisEcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSisEcuActionPerformed(evt);
            }
        });
        getContentPane().add(botonSisEcu);
        botonSisEcu.setBounds(310, 370, 430, 120);

        botonInterp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Temas 3.png"))); // NOI18N
        botonInterp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInterpActionPerformed(evt);
            }
        });
        getContentPane().add(botonInterp);
        botonInterp.setBounds(310, 510, 430, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Temas.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 1030, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        home.setSize(1024,768);
        home.setResizable(false);
        home.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonEc1VarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEc1VarActionPerformed
        // TODO add your handling code here:
        Ecuaciones1Var ec = new Ecuaciones1Var();
        ec.setVisible(true);
        ec.setSize(1024,768);
        ec.setResizable(false);
        ec.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonEc1VarActionPerformed

    private void botonSisEcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSisEcuActionPerformed
        // TODO add your handling code here:
        SistemaEcuaciones se = new SistemaEcuaciones();
        se.setVisible(true);
        se.setSize(1024,768);
        se.setResizable(false);
        se.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonSisEcuActionPerformed

    private void botonInterpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInterpActionPerformed
        // TODO add your handling code here:
        Interpolacion in = new Interpolacion();
        in.setVisible(true);
        in.setSize(1024,768);
        in.setResizable(false);
        in.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonInterpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEc1Var;
    private javax.swing.JButton botonInterp;
    private javax.swing.JButton botonSisEcu;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
